# Generated by Django 5.0.1 on 2024-02-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Default Title', max_length=100)),
                ('Add_Address', models.TextField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
            ],
        ),
    ]
