# Generated by Django 5.0.1 on 2024-03-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_add_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quick_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Default Title', max_length=100)),
                ('Add_Address', models.TextField()),
                ('Date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Quick Plan',
                'verbose_name_plural': 'Quick Plans',
            },
        ),
        migrations.AlterModelOptions(
            name='add_appointment',
            options={'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='add_event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
