# Generated by Django 5.0.1 on 2024-03-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_quick_plan_alter_add_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_event',
            name='type',
            field=models.CharField(default='appointment', max_length=100),
        ),
    ]
