# Generated by Django 5.0.1 on 2024-03-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_add_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_event',
            name='type',
        ),
        migrations.AddField(
            model_name='quick_plan',
            name='type',
            field=models.CharField(default='appointment', max_length=100),
        ),
    ]
